<a href="https://colab.research.google.com/github/IamAgranshRastogi/Neural_Network/blob/main/Gates_Using_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#OR Gate using Perceptron Model

In [ ]:
import numpy as np

weight = np.array([1,1])
bias = -0.5
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

def OR_perceptron(x, weight, bias):

    fx = np.dot(weight, x)  + bias

    if fx >= 0:
        return i, 1
    else:
        return i, 0

for i in inputs:
    print(OR_perceptron(i, weight, bias))

(array([0, 0]), 0)
(array([0, 1]), 1)
(array([1, 0]), 1)
(array([1, 1]), 1)


#And Gate Using Percepton Model

In [ ]:
import numpy as np

weight = np.array([1,1])
bias = -1.5
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

def AND_perceptron(x, weight, bias):

    fx = np.dot(weight, x)  + bias

    if fx >= 0:
        return i, 1
    else:
        return i, 0

for i in inputs:
    print(AND_perceptron(i, weight, bias))

(array([0, 0]), 0)
(array([0, 1]), 0)
(array([1, 0]), 0)
(array([1, 1]), 1)
